#pragma once


#define KEYWORD_MODULE    "module"
#define KEYWORD_NAMESPACE "namespace"
#define KEYWORD_IMPORT    "import"
#define KEYWORD_VAR       "var"
#define KEYWORD_FUNC      "func"
#define KEYWORD_STRUCT    "struct"
#define KEYWORD_CLASS     "class"
#define KEYWORD_TYPEDEF   "typedef"
#define KEYWORD_EXPRDEF   "exprdef"
#define KEYWORD_METHOD    "method"
#define KEYWORD_ENUM      "enum"

#define KEYWORD_PUBLIC    "public"
#define KEYWORD_PRIVATE   "private"
#define KEYWORD_STATIC    "static"
#define KEYWORD_CONST     "const"
#define KEYWORD_EXTERN    "externc"
#define KEYWORD_DLLEXPORT "dllexport"
#define KEYWORD_DLLIMPORT "dllimport"
#define KEYWORD_PACKED    "packed"

#define KEYWORD_IF        "if"
#define KEYWORD_ELSE      "else"
#define KEYWORD_FOR       "for"
#define KEYWORD_WHILE	  "while"
#define KEYWORD_RETURN	  "return"
#define KEYWORD_BREAK	  "break"
#define KEYWORD_CONTINUE  "continue"
#define KEYWORD_DEFER	  "defer"

#define KEYWORD_AS        "as"
#define KEYWORD_SIZEOF	  "sizeof"
#define KEYWORD_ALLOCA	  "alloca"
#define KEYWORD_MALLOC	  "new"
#define KEYWORD_STACKNEW  "snew"
#define KEYWORD_FREE	  "delete"

#define KEYWORD_TRUE      "true"
#define KEYWORD_FALSE	  "false"
#define KEYWORD_NULL	  "null"

#define KEYWORD_VOID      "void"

#define KEYWORD_INT8      "int8"
#define KEYWORD_INT16	  "int16"
#define KEYWORD_INT32	  "int32"
#define KEYWORD_INT64	  "int64"
#define KEYWORD_INT128	  "int128"

#define KEYWORD_CHAR      "char"
#define KEYWORD_SHORT	  "short"
#define KEYWORD_INT	      "int"
#define KEYWORD_LONG	  "long"

#define KEYWORD_UINT8     "uint8"
#define KEYWORD_UINT16	  "uint16"
#define KEYWORD_UINT32	  "uint32"
#define KEYWORD_UINT64	  "uint64"
#define KEYWORD_UINT128	  "uint128"

#define KEYWORD_BYTE	  "byte"
#define KEYWORD_UCHAR     "uchar"
#define KEYWORD_USHORT	  "ushort"
#define KEYWORD_UINT	  "uint"
#define KEYWORD_ULONG	  "ulong"

#define KEYWORD_BOOL      "bool"
#define KEYWORD_STRING    "string"

#define KEYWORD_FLOAT16   "float16"
#define KEYWORD_FLOAT32   "float32"
#define KEYWORD_FLOAT64   "float64"
#define KEYWORD_FLOAT80	  "float80"
#define KEYWORD_FLOAT128  "float128"

#define KEYWORD_HALF      "half"
#define KEYWORD_FLOAT     "float"
#define KEYWORD_DOUBLE    "double"
#define KEYWORD_DECIMAL	  "decimal"

#define KEYWORD_PTR       "Ptr"
#define KEYWORD_ARRAY     "Array"
#define KEYWORD_FUNC_TYPE "fntype"
